### ISSUE TITLE
OS appears to run fine, "device is corrupt" message on boot

### ISSUE THREAD

**Issue by BringerofD** [GrapheneOS/matrix.grapheneos.org#11]
Device: Pixel 6a

I just finished the flashing process, but every time I power on or restart the device I receive a red "this device is corrupt" message. Once I hit the power button to continue, I get the next yellow screen telling me that I'm booting a different OS. I hear the second part is normal, but how do I get rid of the "corrupt" message? Once I click through both messages the OS boots without issue as far as I can tell and the phone runs just fine.

Is there a solution to this, is this just a fact of life with graphene, or do I just need to do a factory reset and flash it all over again?

Any help would be much appreciated, thanks!

**Comment by thestinger** [comment]
You need to stop using the device and complete the installation process correctly. Your installation is corrupt and should not be used. You will end up losing your data or worse. It's not running fine. I suggest that you flash the stock OS, boot it and then flash GrapheneOS again. Make sure to use our official instructions.

**Comment by thestinger** [comment]
We think this might be a firmware bug leading to a broken installation. Suggest you flash stock OS, boot, then GrapheneOS because that seems to be a working way of dealing with it.
